create table public.lessons (
    id bigint generated by default as identity not null,
    module_id bigint null,
    title text null,
    description text null,
    content text null,
    "position" bigint null,
    starter_code text null,
    validation_rules json null,
    published boolean null default false,
    created_at timestamp with time zone not null default now(),
    constraint lessons_pkey primary key (id),
    constraint lessons_position_key unique ("position"),
    constraint lessons_title_key unique (title),
    constraint lessons_module_id_fkey foreign KEY (module_id) references modules (id)
) TABLESPACE pg_default;

alter policy "Anyone can read lessons"
on "public"."lessons"
to public
using (
    true
);

create table public.modules (
    id bigint generated by default as identity not null,
    title text null,
    description text null,
    "position" bigint null,
    published boolean null default false,
    created_at timestamp with time zone not null default now(),
    constraint modules_pkey primary key (id),
    constraint modules_position_key unique ("position"),
    constraint modules_title_key unique (title)
) TABLESPACE pg_default;

alter policy "Anyone can read modules"
on "public"."modules"
to public
using (
    true
);


create table public.profiles (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    username text null,
    constraint profiles_pkey primary key (id),
    constraint profiles_username_key unique (username)
) TABLESPACE pg_default;

alter policy "Users can read/write their own profile"
on "public"."profiles"
to authenticated
using (
  true
);

create table public.progresses (
    id bigint generated by default as identity not null,
    user_id bigint null,
    lesson_id bigint null,
    status text null,
    attempts bigint null,
    completed_at timestamp with time zone null,
    updated_at timestamp with time zone null,
    constraint progresses_pkey primary key (id),
    constraint progresses_lesson_id_fkey foreign KEY (lesson_id) references lessons (id),
    constraint progresses_user_id_fkey foreign KEY (user_id) references profiles (id)
) TABLESPACE pg_default;

alter policy "Users can read/write their own progress"
on "public"."progresses"
to public
using (
  true
);


INSERT INTO public.modules (id, title, description, "position", published, created_at)
VALUES (1, '2.1 Basic HTML syntax', null, 1, false, '2026-10-09 06:57:39.310419+00'),
       (2, ' Good document structure', null, 2, false, '2026-10-09 06:58:00.343983+00'),
       (3, 'Lists', null, 3, false, '2026-10-09 06:58:11.33421+00'),
       (5, 'Advanced text techniques ', null, 4, false, '2026-10-09 06:58:31.148325+00'),
       (6, 'Links', null, 5, false, '2026-10-09 06:58:47.027033+00'),
       (7, 'Media', null, 6, false, '2026-10-09 06:58:57.891447+00'),
       (8, 'Other interactive elements', null, 7, false, '2026-10-09 06:59:14.157967+00'),
       (9, 'HTML tables', null, 8, false, '2026-10-09 06:59:26.858736+00'),
       (10, 'Debugging HTML', null, 9, false, '2026-10-09 06:59:36.846162+00');